# Generated by Django 6.0 on 2025-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived_by_customer',
            field=models.BooleanField(default=False, help_text='Order archived from customer view but still visible to restaurant owner'),
        ),
    ]
